env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  "@typescript-eslint/promise-function-async": "off"
